{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import squarify\n",
    "import os\n",
    "    \n",
    "# Main libraries that we will use in this kernel\n",
    "import datetime\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "\n",
    "# # garbage collector: free some memory is needed\n",
    "import gc\n",
    "import matplotlib\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "\n",
    "# statistical package and some useful functions to analyze our timeseries\n",
    "from statsmodels.tsa.stattools import pacf\n",
    "from statsmodels.graphics.tsaplots import plot_acf, plot_pacf\n",
    "from statsmodels.tsa.seasonal import seasonal_decompose\n",
    "import statsmodels.tsa.stattools as stattools\n",
    "\n",
    "import time\n",
    "\n",
    "from string import punctuation\n",
    "from sklearn.preprocessing import LabelEncoder\n",
    "from sklearn.linear_model import LinearRegression\n",
    "\n",
    "import warnings\n",
    "warnings.filterwarnings(\"ignore\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "# python core library for machine learning and data science\n",
    "from sklearn.pipeline import Pipeline\n",
    "from sklearn.preprocessing import StandardScaler, MinMaxScaler\n",
    "from sklearn.base import BaseEstimator, TransformerMixin\n",
    "from sklearn.impute import KNNImputer, SimpleImputer\n",
    "from sklearn.cluster import KMeans"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "#full_2 = pd.read_pickle('./full_2.pickle')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>id_cliente</th>\n",
       "      <th>pk_cid_x</th>\n",
       "      <th>pk_partition_x</th>\n",
       "      <th>Productos</th>\n",
       "      <th>Ventas_cant</th>\n",
       "      <th>Precios</th>\n",
       "      <th>Familia_prod</th>\n",
       "      <th>Ingresos</th>\n",
       "      <th>pk_cid_y</th>\n",
       "      <th>pk_partition_y</th>\n",
       "      <th>...</th>\n",
       "      <th>días_encartera</th>\n",
       "      <th>pk_cid</th>\n",
       "      <th>pk_partition</th>\n",
       "      <th>country_id</th>\n",
       "      <th>region_code</th>\n",
       "      <th>gender</th>\n",
       "      <th>age</th>\n",
       "      <th>deceased</th>\n",
       "      <th>date</th>\n",
       "      <th>Month</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>10000282018-01-28</td>\n",
       "      <td>1000028</td>\n",
       "      <td>2018-01-28</td>\n",
       "      <td>short_term_deposit</td>\n",
       "      <td>0.0</td>\n",
       "      <td>40</td>\n",
       "      <td>Inversión</td>\n",
       "      <td>0.0</td>\n",
       "      <td>1000028</td>\n",
       "      <td>2018-01-28</td>\n",
       "      <td>...</td>\n",
       "      <td>390.0</td>\n",
       "      <td>1000028</td>\n",
       "      <td>2018-01-28</td>\n",
       "      <td>ES</td>\n",
       "      <td>28.0</td>\n",
       "      <td>H</td>\n",
       "      <td>43</td>\n",
       "      <td>N</td>\n",
       "      <td>2018-01-28</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>10000282018-02-28</td>\n",
       "      <td>1000028</td>\n",
       "      <td>2018-02-28</td>\n",
       "      <td>short_term_deposit</td>\n",
       "      <td>0.0</td>\n",
       "      <td>40</td>\n",
       "      <td>Inversión</td>\n",
       "      <td>0.0</td>\n",
       "      <td>1000028</td>\n",
       "      <td>2018-02-28</td>\n",
       "      <td>...</td>\n",
       "      <td>421.0</td>\n",
       "      <td>1000028</td>\n",
       "      <td>2018-02-28</td>\n",
       "      <td>ES</td>\n",
       "      <td>28.0</td>\n",
       "      <td>H</td>\n",
       "      <td>43</td>\n",
       "      <td>N</td>\n",
       "      <td>2018-02-28</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>10000282018-03-28</td>\n",
       "      <td>1000028</td>\n",
       "      <td>2018-03-28</td>\n",
       "      <td>short_term_deposit</td>\n",
       "      <td>0.0</td>\n",
       "      <td>40</td>\n",
       "      <td>Inversión</td>\n",
       "      <td>0.0</td>\n",
       "      <td>1000028</td>\n",
       "      <td>2018-03-28</td>\n",
       "      <td>...</td>\n",
       "      <td>449.0</td>\n",
       "      <td>1000028</td>\n",
       "      <td>2018-03-28</td>\n",
       "      <td>ES</td>\n",
       "      <td>28.0</td>\n",
       "      <td>H</td>\n",
       "      <td>43</td>\n",
       "      <td>N</td>\n",
       "      <td>2018-03-28</td>\n",
       "      <td>3</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>10000282018-04-28</td>\n",
       "      <td>1000028</td>\n",
       "      <td>2018-04-28</td>\n",
       "      <td>short_term_deposit</td>\n",
       "      <td>0.0</td>\n",
       "      <td>40</td>\n",
       "      <td>Inversión</td>\n",
       "      <td>0.0</td>\n",
       "      <td>1000028</td>\n",
       "      <td>2018-04-28</td>\n",
       "      <td>...</td>\n",
       "      <td>480.0</td>\n",
       "      <td>1000028</td>\n",
       "      <td>2018-04-28</td>\n",
       "      <td>ES</td>\n",
       "      <td>28.0</td>\n",
       "      <td>H</td>\n",
       "      <td>43</td>\n",
       "      <td>N</td>\n",
       "      <td>2018-04-28</td>\n",
       "      <td>4</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>10000282018-05-28</td>\n",
       "      <td>1000028</td>\n",
       "      <td>2018-05-28</td>\n",
       "      <td>short_term_deposit</td>\n",
       "      <td>0.0</td>\n",
       "      <td>40</td>\n",
       "      <td>Inversión</td>\n",
       "      <td>0.0</td>\n",
       "      <td>1000028</td>\n",
       "      <td>2018-05-28</td>\n",
       "      <td>...</td>\n",
       "      <td>510.0</td>\n",
       "      <td>1000028</td>\n",
       "      <td>2018-05-28</td>\n",
       "      <td>ES</td>\n",
       "      <td>28.0</td>\n",
       "      <td>H</td>\n",
       "      <td>43</td>\n",
       "      <td>N</td>\n",
       "      <td>2018-05-28</td>\n",
       "      <td>5</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>5 rows × 23 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "          id_cliente pk_cid_x pk_partition_x           Productos  Ventas_cant  \\\n",
       "0  10000282018-01-28  1000028     2018-01-28  short_term_deposit          0.0   \n",
       "1  10000282018-02-28  1000028     2018-02-28  short_term_deposit          0.0   \n",
       "2  10000282018-03-28  1000028     2018-03-28  short_term_deposit          0.0   \n",
       "3  10000282018-04-28  1000028     2018-04-28  short_term_deposit          0.0   \n",
       "4  10000282018-05-28  1000028     2018-05-28  short_term_deposit          0.0   \n",
       "\n",
       "   Precios Familia_prod  Ingresos pk_cid_y pk_partition_y  ... días_encartera  \\\n",
       "0       40    Inversión       0.0  1000028     2018-01-28  ...          390.0   \n",
       "1       40    Inversión       0.0  1000028     2018-02-28  ...          421.0   \n",
       "2       40    Inversión       0.0  1000028     2018-03-28  ...          449.0   \n",
       "3       40    Inversión       0.0  1000028     2018-04-28  ...          480.0   \n",
       "4       40    Inversión       0.0  1000028     2018-05-28  ...          510.0   \n",
       "\n",
       "    pk_cid pk_partition  country_id region_code gender age  deceased  \\\n",
       "0  1000028   2018-01-28          ES        28.0      H  43         N   \n",
       "1  1000028   2018-02-28          ES        28.0      H  43         N   \n",
       "2  1000028   2018-03-28          ES        28.0      H  43         N   \n",
       "3  1000028   2018-04-28          ES        28.0      H  43         N   \n",
       "4  1000028   2018-05-28          ES        28.0      H  43         N   \n",
       "\n",
       "        date  Month  \n",
       "0 2018-01-28      1  \n",
       "1 2018-02-28      2  \n",
       "2 2018-03-28      3  \n",
       "3 2018-04-28      4  \n",
       "4 2018-05-28      5  \n",
       "\n",
       "[5 rows x 23 columns]"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#full_2.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "ename": "KeyError",
     "evalue": "\"['pk_cid_y' 'pk_cid_x' 'pk_partition_x' 'pk_partition_y'] not found in axis\"",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mKeyError\u001b[0m                                  Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-7-552836c7ba3b>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[1;32m----> 1\u001b[1;33m \u001b[0mfull_2\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mdrop\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;34m'pk_cid_y'\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;34m'pk_cid_x'\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;34m'pk_partition_x'\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;34m'pk_partition_y'\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0maxis\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;36m1\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0minplace\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;32mTrue\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;32m~\\anaconda3\\lib\\site-packages\\pandas\\core\\frame.py\u001b[0m in \u001b[0;36mdrop\u001b[1;34m(self, labels, axis, index, columns, level, inplace, errors)\u001b[0m\n\u001b[0;32m   4161\u001b[0m                 \u001b[0mweight\u001b[0m  \u001b[1;36m1.0\u001b[0m     \u001b[1;36m0.8\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   4162\u001b[0m         \"\"\"\n\u001b[1;32m-> 4163\u001b[1;33m         return super().drop(\n\u001b[0m\u001b[0;32m   4164\u001b[0m             \u001b[0mlabels\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mlabels\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   4165\u001b[0m             \u001b[0maxis\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0maxis\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\anaconda3\\lib\\site-packages\\pandas\\core\\generic.py\u001b[0m in \u001b[0;36mdrop\u001b[1;34m(self, labels, axis, index, columns, level, inplace, errors)\u001b[0m\n\u001b[0;32m   3885\u001b[0m         \u001b[1;32mfor\u001b[0m \u001b[0maxis\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mlabels\u001b[0m \u001b[1;32min\u001b[0m \u001b[0maxes\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mitems\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   3886\u001b[0m             \u001b[1;32mif\u001b[0m \u001b[0mlabels\u001b[0m \u001b[1;32mis\u001b[0m \u001b[1;32mnot\u001b[0m \u001b[1;32mNone\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 3887\u001b[1;33m                 \u001b[0mobj\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mobj\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_drop_axis\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mlabels\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0maxis\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mlevel\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mlevel\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0merrors\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0merrors\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   3888\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   3889\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[0minplace\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\anaconda3\\lib\\site-packages\\pandas\\core\\generic.py\u001b[0m in \u001b[0;36m_drop_axis\u001b[1;34m(self, labels, axis, level, errors)\u001b[0m\n\u001b[0;32m   3919\u001b[0m                 \u001b[0mnew_axis\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0maxis\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mdrop\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mlabels\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mlevel\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mlevel\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0merrors\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0merrors\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   3920\u001b[0m             \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 3921\u001b[1;33m                 \u001b[0mnew_axis\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0maxis\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mdrop\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mlabels\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0merrors\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0merrors\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   3922\u001b[0m             \u001b[0mresult\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mreindex\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m**\u001b[0m\u001b[1;33m{\u001b[0m\u001b[0maxis_name\u001b[0m\u001b[1;33m:\u001b[0m \u001b[0mnew_axis\u001b[0m\u001b[1;33m}\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   3923\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\anaconda3\\lib\\site-packages\\pandas\\core\\indexes\\base.py\u001b[0m in \u001b[0;36mdrop\u001b[1;34m(self, labels, errors)\u001b[0m\n\u001b[0;32m   5280\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[0mmask\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0many\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   5281\u001b[0m             \u001b[1;32mif\u001b[0m \u001b[0merrors\u001b[0m \u001b[1;33m!=\u001b[0m \u001b[1;34m\"ignore\"\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 5282\u001b[1;33m                 \u001b[1;32mraise\u001b[0m \u001b[0mKeyError\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34mf\"{labels[mask]} not found in axis\"\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   5283\u001b[0m             \u001b[0mindexer\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mindexer\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;33m~\u001b[0m\u001b[0mmask\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   5284\u001b[0m         \u001b[1;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mdelete\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mindexer\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mKeyError\u001b[0m: \"['pk_cid_y' 'pk_cid_x' 'pk_partition_x' 'pk_partition_y'] not found in axis\""
     ]
    }
   ],
   "source": [
    "#full_2.drop(['pk_cid_y','pk_cid_x','pk_partition_x','pk_partition_y'], axis=1, inplace=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "full_2.drop(['id_cliente','pk_partition','active_customer'],axis=1,inplace=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Productos</th>\n",
       "      <th>Ventas_cant</th>\n",
       "      <th>Precios</th>\n",
       "      <th>Familia_prod</th>\n",
       "      <th>Ingresos</th>\n",
       "      <th>entry_date</th>\n",
       "      <th>entry_channel</th>\n",
       "      <th>días_encartera</th>\n",
       "      <th>pk_cid</th>\n",
       "      <th>country_id</th>\n",
       "      <th>region_code</th>\n",
       "      <th>gender</th>\n",
       "      <th>age</th>\n",
       "      <th>deceased</th>\n",
       "      <th>date</th>\n",
       "      <th>Month</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>22134</th>\n",
       "      <td>short_term_deposit</td>\n",
       "      <td>1.0</td>\n",
       "      <td>40</td>\n",
       "      <td>Inversión</td>\n",
       "      <td>40.0</td>\n",
       "      <td>2018-04-08</td>\n",
       "      <td>KHK</td>\n",
       "      <td>20.0</td>\n",
       "      <td>100296</td>\n",
       "      <td>ES</td>\n",
       "      <td>28.0</td>\n",
       "      <td>V</td>\n",
       "      <td>46</td>\n",
       "      <td>N</td>\n",
       "      <td>2018-04-28</td>\n",
       "      <td>4</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>22135</th>\n",
       "      <td>short_term_deposit</td>\n",
       "      <td>1.0</td>\n",
       "      <td>40</td>\n",
       "      <td>Inversión</td>\n",
       "      <td>40.0</td>\n",
       "      <td>2018-04-08</td>\n",
       "      <td>KHK</td>\n",
       "      <td>50.0</td>\n",
       "      <td>100296</td>\n",
       "      <td>ES</td>\n",
       "      <td>28.0</td>\n",
       "      <td>V</td>\n",
       "      <td>46</td>\n",
       "      <td>N</td>\n",
       "      <td>2018-05-28</td>\n",
       "      <td>5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>22136</th>\n",
       "      <td>short_term_deposit</td>\n",
       "      <td>1.0</td>\n",
       "      <td>40</td>\n",
       "      <td>Inversión</td>\n",
       "      <td>40.0</td>\n",
       "      <td>2018-04-08</td>\n",
       "      <td>KHK</td>\n",
       "      <td>81.0</td>\n",
       "      <td>100296</td>\n",
       "      <td>ES</td>\n",
       "      <td>28.0</td>\n",
       "      <td>V</td>\n",
       "      <td>46</td>\n",
       "      <td>N</td>\n",
       "      <td>2018-06-28</td>\n",
       "      <td>6</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>27826</th>\n",
       "      <td>short_term_deposit</td>\n",
       "      <td>1.0</td>\n",
       "      <td>40</td>\n",
       "      <td>Inversión</td>\n",
       "      <td>40.0</td>\n",
       "      <td>2015-01-30</td>\n",
       "      <td>KHM</td>\n",
       "      <td>1337.0</td>\n",
       "      <td>1003705</td>\n",
       "      <td>ES</td>\n",
       "      <td>28.0</td>\n",
       "      <td>H</td>\n",
       "      <td>33</td>\n",
       "      <td>N</td>\n",
       "      <td>2018-09-28</td>\n",
       "      <td>9</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>27827</th>\n",
       "      <td>short_term_deposit</td>\n",
       "      <td>1.0</td>\n",
       "      <td>40</td>\n",
       "      <td>Inversión</td>\n",
       "      <td>40.0</td>\n",
       "      <td>2015-01-30</td>\n",
       "      <td>KHM</td>\n",
       "      <td>1367.0</td>\n",
       "      <td>1003705</td>\n",
       "      <td>ES</td>\n",
       "      <td>28.0</td>\n",
       "      <td>H</td>\n",
       "      <td>33</td>\n",
       "      <td>N</td>\n",
       "      <td>2018-10-28</td>\n",
       "      <td>10</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                Productos  Ventas_cant  Precios Familia_prod  Ingresos  \\\n",
       "22134  short_term_deposit          1.0       40    Inversión      40.0   \n",
       "22135  short_term_deposit          1.0       40    Inversión      40.0   \n",
       "22136  short_term_deposit          1.0       40    Inversión      40.0   \n",
       "27826  short_term_deposit          1.0       40    Inversión      40.0   \n",
       "27827  short_term_deposit          1.0       40    Inversión      40.0   \n",
       "\n",
       "      entry_date entry_channel  días_encartera   pk_cid country_id  \\\n",
       "22134 2018-04-08           KHK            20.0   100296         ES   \n",
       "22135 2018-04-08           KHK            50.0   100296         ES   \n",
       "22136 2018-04-08           KHK            81.0   100296         ES   \n",
       "27826 2015-01-30           KHM          1337.0  1003705         ES   \n",
       "27827 2015-01-30           KHM          1367.0  1003705         ES   \n",
       "\n",
       "       region_code gender  age deceased       date  Month  \n",
       "22134         28.0      V   46        N 2018-04-28      4  \n",
       "22135         28.0      V   46        N 2018-05-28      5  \n",
       "22136         28.0      V   46        N 2018-06-28      6  \n",
       "27826         28.0      H   33        N 2018-09-28      9  \n",
       "27827         28.0      H   33        N 2018-10-28     10  "
      ]
     },
     "execution_count": 26,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "full_3=full_2[full_2['Ingresos']>0]\n",
    "full_3.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Productos</th>\n",
       "      <th>Ventas_cant</th>\n",
       "      <th>Precios</th>\n",
       "      <th>Familia_prod</th>\n",
       "      <th>Ingresos</th>\n",
       "      <th>entry_date</th>\n",
       "      <th>entry_channel</th>\n",
       "      <th>días_encartera</th>\n",
       "      <th>pk_cid</th>\n",
       "      <th>country_id</th>\n",
       "      <th>region_code</th>\n",
       "      <th>gender</th>\n",
       "      <th>age</th>\n",
       "      <th>deceased</th>\n",
       "      <th>date</th>\n",
       "      <th>Month</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>22134</th>\n",
       "      <td>short_term_deposit</td>\n",
       "      <td>1.0</td>\n",
       "      <td>40</td>\n",
       "      <td>Inversión</td>\n",
       "      <td>40.0</td>\n",
       "      <td>2018-04-08</td>\n",
       "      <td>KHK</td>\n",
       "      <td>20.0</td>\n",
       "      <td>100296</td>\n",
       "      <td>ES</td>\n",
       "      <td>28.0</td>\n",
       "      <td>V</td>\n",
       "      <td>46</td>\n",
       "      <td>N</td>\n",
       "      <td>2018-04-28</td>\n",
       "      <td>4</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>22135</th>\n",
       "      <td>short_term_deposit</td>\n",
       "      <td>1.0</td>\n",
       "      <td>40</td>\n",
       "      <td>Inversión</td>\n",
       "      <td>40.0</td>\n",
       "      <td>2018-04-08</td>\n",
       "      <td>KHK</td>\n",
       "      <td>50.0</td>\n",
       "      <td>100296</td>\n",
       "      <td>ES</td>\n",
       "      <td>28.0</td>\n",
       "      <td>V</td>\n",
       "      <td>46</td>\n",
       "      <td>N</td>\n",
       "      <td>2018-05-28</td>\n",
       "      <td>5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>22136</th>\n",
       "      <td>short_term_deposit</td>\n",
       "      <td>1.0</td>\n",
       "      <td>40</td>\n",
       "      <td>Inversión</td>\n",
       "      <td>40.0</td>\n",
       "      <td>2018-04-08</td>\n",
       "      <td>KHK</td>\n",
       "      <td>81.0</td>\n",
       "      <td>100296</td>\n",
       "      <td>ES</td>\n",
       "      <td>28.0</td>\n",
       "      <td>V</td>\n",
       "      <td>46</td>\n",
       "      <td>N</td>\n",
       "      <td>2018-06-28</td>\n",
       "      <td>6</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>27826</th>\n",
       "      <td>short_term_deposit</td>\n",
       "      <td>1.0</td>\n",
       "      <td>40</td>\n",
       "      <td>Inversión</td>\n",
       "      <td>40.0</td>\n",
       "      <td>2015-01-30</td>\n",
       "      <td>KHM</td>\n",
       "      <td>1337.0</td>\n",
       "      <td>1003705</td>\n",
       "      <td>ES</td>\n",
       "      <td>28.0</td>\n",
       "      <td>H</td>\n",
       "      <td>33</td>\n",
       "      <td>N</td>\n",
       "      <td>2018-09-28</td>\n",
       "      <td>9</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>27827</th>\n",
       "      <td>short_term_deposit</td>\n",
       "      <td>1.0</td>\n",
       "      <td>40</td>\n",
       "      <td>Inversión</td>\n",
       "      <td>40.0</td>\n",
       "      <td>2015-01-30</td>\n",
       "      <td>KHM</td>\n",
       "      <td>1367.0</td>\n",
       "      <td>1003705</td>\n",
       "      <td>ES</td>\n",
       "      <td>28.0</td>\n",
       "      <td>H</td>\n",
       "      <td>33</td>\n",
       "      <td>N</td>\n",
       "      <td>2018-10-28</td>\n",
       "      <td>10</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                Productos  Ventas_cant  Precios Familia_prod  Ingresos  \\\n",
       "22134  short_term_deposit          1.0       40    Inversión      40.0   \n",
       "22135  short_term_deposit          1.0       40    Inversión      40.0   \n",
       "22136  short_term_deposit          1.0       40    Inversión      40.0   \n",
       "27826  short_term_deposit          1.0       40    Inversión      40.0   \n",
       "27827  short_term_deposit          1.0       40    Inversión      40.0   \n",
       "\n",
       "      entry_date entry_channel  días_encartera   pk_cid country_id  \\\n",
       "22134 2018-04-08           KHK            20.0   100296         ES   \n",
       "22135 2018-04-08           KHK            50.0   100296         ES   \n",
       "22136 2018-04-08           KHK            81.0   100296         ES   \n",
       "27826 2015-01-30           KHM          1337.0  1003705         ES   \n",
       "27827 2015-01-30           KHM          1367.0  1003705         ES   \n",
       "\n",
       "       region_code gender  age deceased       date  Month  \n",
       "22134         28.0      V   46        N 2018-04-28      4  \n",
       "22135         28.0      V   46        N 2018-05-28      5  \n",
       "22136         28.0      V   46        N 2018-06-28      6  \n",
       "27826         28.0      H   33        N 2018-09-28      9  \n",
       "27827         28.0      H   33        N 2018-10-28     10  "
      ]
     },
     "execution_count": 27,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "full_3.groupby('pk_cid')\n",
    "full_3.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Productos</th>\n",
       "      <th>Ventas_cant</th>\n",
       "      <th>Precios</th>\n",
       "      <th>Familia_prod</th>\n",
       "      <th>Ingresos</th>\n",
       "      <th>entry_date</th>\n",
       "      <th>entry_channel</th>\n",
       "      <th>días_encartera</th>\n",
       "      <th>pk_cid</th>\n",
       "      <th>country_id</th>\n",
       "      <th>region_code</th>\n",
       "      <th>gender</th>\n",
       "      <th>age</th>\n",
       "      <th>deceased</th>\n",
       "      <th>date</th>\n",
       "      <th>Month</th>\n",
       "      <th>days_between</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>22134</th>\n",
       "      <td>short_term_deposit</td>\n",
       "      <td>1.0</td>\n",
       "      <td>40</td>\n",
       "      <td>Inversión</td>\n",
       "      <td>40.0</td>\n",
       "      <td>2018-04-08</td>\n",
       "      <td>KHK</td>\n",
       "      <td>20.0</td>\n",
       "      <td>100296</td>\n",
       "      <td>ES</td>\n",
       "      <td>28.0</td>\n",
       "      <td>V</td>\n",
       "      <td>46</td>\n",
       "      <td>N</td>\n",
       "      <td>2018-04-28</td>\n",
       "      <td>4</td>\n",
       "      <td>NaT</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>22135</th>\n",
       "      <td>short_term_deposit</td>\n",
       "      <td>1.0</td>\n",
       "      <td>40</td>\n",
       "      <td>Inversión</td>\n",
       "      <td>40.0</td>\n",
       "      <td>2018-04-08</td>\n",
       "      <td>KHK</td>\n",
       "      <td>50.0</td>\n",
       "      <td>100296</td>\n",
       "      <td>ES</td>\n",
       "      <td>28.0</td>\n",
       "      <td>V</td>\n",
       "      <td>46</td>\n",
       "      <td>N</td>\n",
       "      <td>2018-05-28</td>\n",
       "      <td>5</td>\n",
       "      <td>30 days</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>22136</th>\n",
       "      <td>short_term_deposit</td>\n",
       "      <td>1.0</td>\n",
       "      <td>40</td>\n",
       "      <td>Inversión</td>\n",
       "      <td>40.0</td>\n",
       "      <td>2018-04-08</td>\n",
       "      <td>KHK</td>\n",
       "      <td>81.0</td>\n",
       "      <td>100296</td>\n",
       "      <td>ES</td>\n",
       "      <td>28.0</td>\n",
       "      <td>V</td>\n",
       "      <td>46</td>\n",
       "      <td>N</td>\n",
       "      <td>2018-06-28</td>\n",
       "      <td>6</td>\n",
       "      <td>31 days</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>27826</th>\n",
       "      <td>short_term_deposit</td>\n",
       "      <td>1.0</td>\n",
       "      <td>40</td>\n",
       "      <td>Inversión</td>\n",
       "      <td>40.0</td>\n",
       "      <td>2015-01-30</td>\n",
       "      <td>KHM</td>\n",
       "      <td>1337.0</td>\n",
       "      <td>1003705</td>\n",
       "      <td>ES</td>\n",
       "      <td>28.0</td>\n",
       "      <td>H</td>\n",
       "      <td>33</td>\n",
       "      <td>N</td>\n",
       "      <td>2018-09-28</td>\n",
       "      <td>9</td>\n",
       "      <td>NaT</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>27827</th>\n",
       "      <td>short_term_deposit</td>\n",
       "      <td>1.0</td>\n",
       "      <td>40</td>\n",
       "      <td>Inversión</td>\n",
       "      <td>40.0</td>\n",
       "      <td>2015-01-30</td>\n",
       "      <td>KHM</td>\n",
       "      <td>1367.0</td>\n",
       "      <td>1003705</td>\n",
       "      <td>ES</td>\n",
       "      <td>28.0</td>\n",
       "      <td>H</td>\n",
       "      <td>33</td>\n",
       "      <td>N</td>\n",
       "      <td>2018-10-28</td>\n",
       "      <td>10</td>\n",
       "      <td>30 days</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                Productos  Ventas_cant  Precios Familia_prod  Ingresos  \\\n",
       "22134  short_term_deposit          1.0       40    Inversión      40.0   \n",
       "22135  short_term_deposit          1.0       40    Inversión      40.0   \n",
       "22136  short_term_deposit          1.0       40    Inversión      40.0   \n",
       "27826  short_term_deposit          1.0       40    Inversión      40.0   \n",
       "27827  short_term_deposit          1.0       40    Inversión      40.0   \n",
       "\n",
       "      entry_date entry_channel  días_encartera   pk_cid country_id  \\\n",
       "22134 2018-04-08           KHK            20.0   100296         ES   \n",
       "22135 2018-04-08           KHK            50.0   100296         ES   \n",
       "22136 2018-04-08           KHK            81.0   100296         ES   \n",
       "27826 2015-01-30           KHM          1337.0  1003705         ES   \n",
       "27827 2015-01-30           KHM          1367.0  1003705         ES   \n",
       "\n",
       "       region_code gender  age deceased       date  Month days_between  \n",
       "22134         28.0      V   46        N 2018-04-28      4          NaT  \n",
       "22135         28.0      V   46        N 2018-05-28      5      30 days  \n",
       "22136         28.0      V   46        N 2018-06-28      6      31 days  \n",
       "27826         28.0      H   33        N 2018-09-28      9          NaT  \n",
       "27827         28.0      H   33        N 2018-10-28     10      30 days  "
      ]
     },
     "execution_count": 28,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "full_3['days_between'] = full_3['date']-(full_3.groupby('pk_cid')['date'].shift(1))\n",
    "full_3.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 36,
   "metadata": {},
   "outputs": [],
   "source": [
    "full_3.replace({pd.NaT: \"0 days\"}, inplace=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 37,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Productos</th>\n",
       "      <th>Ventas_cant</th>\n",
       "      <th>Precios</th>\n",
       "      <th>Familia_prod</th>\n",
       "      <th>Ingresos</th>\n",
       "      <th>entry_date</th>\n",
       "      <th>entry_channel</th>\n",
       "      <th>días_encartera</th>\n",
       "      <th>pk_cid</th>\n",
       "      <th>country_id</th>\n",
       "      <th>region_code</th>\n",
       "      <th>gender</th>\n",
       "      <th>age</th>\n",
       "      <th>deceased</th>\n",
       "      <th>date</th>\n",
       "      <th>Month</th>\n",
       "      <th>days_between</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>22134</th>\n",
       "      <td>short_term_deposit</td>\n",
       "      <td>1.0</td>\n",
       "      <td>40</td>\n",
       "      <td>Inversión</td>\n",
       "      <td>40.0</td>\n",
       "      <td>2018-04-08</td>\n",
       "      <td>KHK</td>\n",
       "      <td>20.0</td>\n",
       "      <td>100296</td>\n",
       "      <td>ES</td>\n",
       "      <td>28.0</td>\n",
       "      <td>V</td>\n",
       "      <td>46</td>\n",
       "      <td>N</td>\n",
       "      <td>2018-04-28</td>\n",
       "      <td>4</td>\n",
       "      <td>0 days</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>22135</th>\n",
       "      <td>short_term_deposit</td>\n",
       "      <td>1.0</td>\n",
       "      <td>40</td>\n",
       "      <td>Inversión</td>\n",
       "      <td>40.0</td>\n",
       "      <td>2018-04-08</td>\n",
       "      <td>KHK</td>\n",
       "      <td>50.0</td>\n",
       "      <td>100296</td>\n",
       "      <td>ES</td>\n",
       "      <td>28.0</td>\n",
       "      <td>V</td>\n",
       "      <td>46</td>\n",
       "      <td>N</td>\n",
       "      <td>2018-05-28</td>\n",
       "      <td>5</td>\n",
       "      <td>30 days 00:00:00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>22136</th>\n",
       "      <td>short_term_deposit</td>\n",
       "      <td>1.0</td>\n",
       "      <td>40</td>\n",
       "      <td>Inversión</td>\n",
       "      <td>40.0</td>\n",
       "      <td>2018-04-08</td>\n",
       "      <td>KHK</td>\n",
       "      <td>81.0</td>\n",
       "      <td>100296</td>\n",
       "      <td>ES</td>\n",
       "      <td>28.0</td>\n",
       "      <td>V</td>\n",
       "      <td>46</td>\n",
       "      <td>N</td>\n",
       "      <td>2018-06-28</td>\n",
       "      <td>6</td>\n",
       "      <td>31 days 00:00:00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>27826</th>\n",
       "      <td>short_term_deposit</td>\n",
       "      <td>1.0</td>\n",
       "      <td>40</td>\n",
       "      <td>Inversión</td>\n",
       "      <td>40.0</td>\n",
       "      <td>2015-01-30</td>\n",
       "      <td>KHM</td>\n",
       "      <td>1337.0</td>\n",
       "      <td>1003705</td>\n",
       "      <td>ES</td>\n",
       "      <td>28.0</td>\n",
       "      <td>H</td>\n",
       "      <td>33</td>\n",
       "      <td>N</td>\n",
       "      <td>2018-09-28</td>\n",
       "      <td>9</td>\n",
       "      <td>0 days</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>27827</th>\n",
       "      <td>short_term_deposit</td>\n",
       "      <td>1.0</td>\n",
       "      <td>40</td>\n",
       "      <td>Inversión</td>\n",
       "      <td>40.0</td>\n",
       "      <td>2015-01-30</td>\n",
       "      <td>KHM</td>\n",
       "      <td>1367.0</td>\n",
       "      <td>1003705</td>\n",
       "      <td>ES</td>\n",
       "      <td>28.0</td>\n",
       "      <td>H</td>\n",
       "      <td>33</td>\n",
       "      <td>N</td>\n",
       "      <td>2018-10-28</td>\n",
       "      <td>10</td>\n",
       "      <td>30 days 00:00:00</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                Productos  Ventas_cant  Precios Familia_prod  Ingresos  \\\n",
       "22134  short_term_deposit          1.0       40    Inversión      40.0   \n",
       "22135  short_term_deposit          1.0       40    Inversión      40.0   \n",
       "22136  short_term_deposit          1.0       40    Inversión      40.0   \n",
       "27826  short_term_deposit          1.0       40    Inversión      40.0   \n",
       "27827  short_term_deposit          1.0       40    Inversión      40.0   \n",
       "\n",
       "      entry_date entry_channel  días_encartera   pk_cid country_id  \\\n",
       "22134 2018-04-08           KHK            20.0   100296         ES   \n",
       "22135 2018-04-08           KHK            50.0   100296         ES   \n",
       "22136 2018-04-08           KHK            81.0   100296         ES   \n",
       "27826 2015-01-30           KHM          1337.0  1003705         ES   \n",
       "27827 2015-01-30           KHM          1367.0  1003705         ES   \n",
       "\n",
       "       region_code gender  age deceased       date  Month      days_between  \n",
       "22134         28.0      V   46        N 2018-04-28      4            0 days  \n",
       "22135         28.0      V   46        N 2018-05-28      5  30 days 00:00:00  \n",
       "22136         28.0      V   46        N 2018-06-28      6  31 days 00:00:00  \n",
       "27826         28.0      H   33        N 2018-09-28      9            0 days  \n",
       "27827         28.0      H   33        N 2018-10-28     10  30 days 00:00:00  "
      ]
     },
     "execution_count": 37,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "full_3.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 51,
   "metadata": {},
   "outputs": [],
   "source": [
    "full_3['conteo']=1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 60,
   "metadata": {},
   "outputs": [],
   "source": [
    "full_3['recurrencia'] = full_3.groupby(['pk_cid']).conteo.agg('cumsum')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 61,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Productos</th>\n",
       "      <th>Ventas_cant</th>\n",
       "      <th>Precios</th>\n",
       "      <th>Familia_prod</th>\n",
       "      <th>Ingresos</th>\n",
       "      <th>entry_date</th>\n",
       "      <th>entry_channel</th>\n",
       "      <th>días_encartera</th>\n",
       "      <th>pk_cid</th>\n",
       "      <th>country_id</th>\n",
       "      <th>region_code</th>\n",
       "      <th>gender</th>\n",
       "      <th>age</th>\n",
       "      <th>deceased</th>\n",
       "      <th>date</th>\n",
       "      <th>Month</th>\n",
       "      <th>days_between</th>\n",
       "      <th>conteo</th>\n",
       "      <th>recurrencia</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>22134</th>\n",
       "      <td>short_term_deposit</td>\n",
       "      <td>1.0</td>\n",
       "      <td>40</td>\n",
       "      <td>Inversión</td>\n",
       "      <td>40.0</td>\n",
       "      <td>2018-04-08</td>\n",
       "      <td>KHK</td>\n",
       "      <td>20.0</td>\n",
       "      <td>100296</td>\n",
       "      <td>ES</td>\n",
       "      <td>28.0</td>\n",
       "      <td>V</td>\n",
       "      <td>46</td>\n",
       "      <td>N</td>\n",
       "      <td>2018-04-28</td>\n",
       "      <td>4</td>\n",
       "      <td>0 days</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>22135</th>\n",
       "      <td>short_term_deposit</td>\n",
       "      <td>1.0</td>\n",
       "      <td>40</td>\n",
       "      <td>Inversión</td>\n",
       "      <td>40.0</td>\n",
       "      <td>2018-04-08</td>\n",
       "      <td>KHK</td>\n",
       "      <td>50.0</td>\n",
       "      <td>100296</td>\n",
       "      <td>ES</td>\n",
       "      <td>28.0</td>\n",
       "      <td>V</td>\n",
       "      <td>46</td>\n",
       "      <td>N</td>\n",
       "      <td>2018-05-28</td>\n",
       "      <td>5</td>\n",
       "      <td>30 days 00:00:00</td>\n",
       "      <td>1</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>22136</th>\n",
       "      <td>short_term_deposit</td>\n",
       "      <td>1.0</td>\n",
       "      <td>40</td>\n",
       "      <td>Inversión</td>\n",
       "      <td>40.0</td>\n",
       "      <td>2018-04-08</td>\n",
       "      <td>KHK</td>\n",
       "      <td>81.0</td>\n",
       "      <td>100296</td>\n",
       "      <td>ES</td>\n",
       "      <td>28.0</td>\n",
       "      <td>V</td>\n",
       "      <td>46</td>\n",
       "      <td>N</td>\n",
       "      <td>2018-06-28</td>\n",
       "      <td>6</td>\n",
       "      <td>31 days 00:00:00</td>\n",
       "      <td>1</td>\n",
       "      <td>3</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>27826</th>\n",
       "      <td>short_term_deposit</td>\n",
       "      <td>1.0</td>\n",
       "      <td>40</td>\n",
       "      <td>Inversión</td>\n",
       "      <td>40.0</td>\n",
       "      <td>2015-01-30</td>\n",
       "      <td>KHM</td>\n",
       "      <td>1337.0</td>\n",
       "      <td>1003705</td>\n",
       "      <td>ES</td>\n",
       "      <td>28.0</td>\n",
       "      <td>H</td>\n",
       "      <td>33</td>\n",
       "      <td>N</td>\n",
       "      <td>2018-09-28</td>\n",
       "      <td>9</td>\n",
       "      <td>0 days</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>27827</th>\n",
       "      <td>short_term_deposit</td>\n",
       "      <td>1.0</td>\n",
       "      <td>40</td>\n",
       "      <td>Inversión</td>\n",
       "      <td>40.0</td>\n",
       "      <td>2015-01-30</td>\n",
       "      <td>KHM</td>\n",
       "      <td>1367.0</td>\n",
       "      <td>1003705</td>\n",
       "      <td>ES</td>\n",
       "      <td>28.0</td>\n",
       "      <td>H</td>\n",
       "      <td>33</td>\n",
       "      <td>N</td>\n",
       "      <td>2018-10-28</td>\n",
       "      <td>10</td>\n",
       "      <td>30 days 00:00:00</td>\n",
       "      <td>1</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                Productos  Ventas_cant  Precios Familia_prod  Ingresos  \\\n",
       "22134  short_term_deposit          1.0       40    Inversión      40.0   \n",
       "22135  short_term_deposit          1.0       40    Inversión      40.0   \n",
       "22136  short_term_deposit          1.0       40    Inversión      40.0   \n",
       "27826  short_term_deposit          1.0       40    Inversión      40.0   \n",
       "27827  short_term_deposit          1.0       40    Inversión      40.0   \n",
       "\n",
       "      entry_date entry_channel  días_encartera   pk_cid country_id  \\\n",
       "22134 2018-04-08           KHK            20.0   100296         ES   \n",
       "22135 2018-04-08           KHK            50.0   100296         ES   \n",
       "22136 2018-04-08           KHK            81.0   100296         ES   \n",
       "27826 2015-01-30           KHM          1337.0  1003705         ES   \n",
       "27827 2015-01-30           KHM          1367.0  1003705         ES   \n",
       "\n",
       "       region_code gender  age deceased       date  Month      days_between  \\\n",
       "22134         28.0      V   46        N 2018-04-28      4            0 days   \n",
       "22135         28.0      V   46        N 2018-05-28      5  30 days 00:00:00   \n",
       "22136         28.0      V   46        N 2018-06-28      6  31 days 00:00:00   \n",
       "27826         28.0      H   33        N 2018-09-28      9            0 days   \n",
       "27827         28.0      H   33        N 2018-10-28     10  30 days 00:00:00   \n",
       "\n",
       "       conteo  recurrencia  \n",
       "22134       1            1  \n",
       "22135       1            2  \n",
       "22136       1            3  \n",
       "27826       1            1  \n",
       "27827       1            2  "
      ]
     },
     "execution_count": 61,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "full_3.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 62,
   "metadata": {},
   "outputs": [],
   "source": [
    "full_3.drop('conteo',axis=1,inplace=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 63,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Productos</th>\n",
       "      <th>Ventas_cant</th>\n",
       "      <th>Precios</th>\n",
       "      <th>Familia_prod</th>\n",
       "      <th>Ingresos</th>\n",
       "      <th>entry_date</th>\n",
       "      <th>entry_channel</th>\n",
       "      <th>días_encartera</th>\n",
       "      <th>pk_cid</th>\n",
       "      <th>country_id</th>\n",
       "      <th>region_code</th>\n",
       "      <th>gender</th>\n",
       "      <th>age</th>\n",
       "      <th>deceased</th>\n",
       "      <th>date</th>\n",
       "      <th>Month</th>\n",
       "      <th>days_between</th>\n",
       "      <th>recurrencia</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>22134</th>\n",
       "      <td>short_term_deposit</td>\n",
       "      <td>1.0</td>\n",
       "      <td>40</td>\n",
       "      <td>Inversión</td>\n",
       "      <td>40.0</td>\n",
       "      <td>2018-04-08</td>\n",
       "      <td>KHK</td>\n",
       "      <td>20.0</td>\n",
       "      <td>100296</td>\n",
       "      <td>ES</td>\n",
       "      <td>28.0</td>\n",
       "      <td>V</td>\n",
       "      <td>46</td>\n",
       "      <td>N</td>\n",
       "      <td>2018-04-28</td>\n",
       "      <td>4</td>\n",
       "      <td>0 days</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>22135</th>\n",
       "      <td>short_term_deposit</td>\n",
       "      <td>1.0</td>\n",
       "      <td>40</td>\n",
       "      <td>Inversión</td>\n",
       "      <td>40.0</td>\n",
       "      <td>2018-04-08</td>\n",
       "      <td>KHK</td>\n",
       "      <td>50.0</td>\n",
       "      <td>100296</td>\n",
       "      <td>ES</td>\n",
       "      <td>28.0</td>\n",
       "      <td>V</td>\n",
       "      <td>46</td>\n",
       "      <td>N</td>\n",
       "      <td>2018-05-28</td>\n",
       "      <td>5</td>\n",
       "      <td>30 days 00:00:00</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>22136</th>\n",
       "      <td>short_term_deposit</td>\n",
       "      <td>1.0</td>\n",
       "      <td>40</td>\n",
       "      <td>Inversión</td>\n",
       "      <td>40.0</td>\n",
       "      <td>2018-04-08</td>\n",
       "      <td>KHK</td>\n",
       "      <td>81.0</td>\n",
       "      <td>100296</td>\n",
       "      <td>ES</td>\n",
       "      <td>28.0</td>\n",
       "      <td>V</td>\n",
       "      <td>46</td>\n",
       "      <td>N</td>\n",
       "      <td>2018-06-28</td>\n",
       "      <td>6</td>\n",
       "      <td>31 days 00:00:00</td>\n",
       "      <td>3</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>27826</th>\n",
       "      <td>short_term_deposit</td>\n",
       "      <td>1.0</td>\n",
       "      <td>40</td>\n",
       "      <td>Inversión</td>\n",
       "      <td>40.0</td>\n",
       "      <td>2015-01-30</td>\n",
       "      <td>KHM</td>\n",
       "      <td>1337.0</td>\n",
       "      <td>1003705</td>\n",
       "      <td>ES</td>\n",
       "      <td>28.0</td>\n",
       "      <td>H</td>\n",
       "      <td>33</td>\n",
       "      <td>N</td>\n",
       "      <td>2018-09-28</td>\n",
       "      <td>9</td>\n",
       "      <td>0 days</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>27827</th>\n",
       "      <td>short_term_deposit</td>\n",
       "      <td>1.0</td>\n",
       "      <td>40</td>\n",
       "      <td>Inversión</td>\n",
       "      <td>40.0</td>\n",
       "      <td>2015-01-30</td>\n",
       "      <td>KHM</td>\n",
       "      <td>1367.0</td>\n",
       "      <td>1003705</td>\n",
       "      <td>ES</td>\n",
       "      <td>28.0</td>\n",
       "      <td>H</td>\n",
       "      <td>33</td>\n",
       "      <td>N</td>\n",
       "      <td>2018-10-28</td>\n",
       "      <td>10</td>\n",
       "      <td>30 days 00:00:00</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                Productos  Ventas_cant  Precios Familia_prod  Ingresos  \\\n",
       "22134  short_term_deposit          1.0       40    Inversión      40.0   \n",
       "22135  short_term_deposit          1.0       40    Inversión      40.0   \n",
       "22136  short_term_deposit          1.0       40    Inversión      40.0   \n",
       "27826  short_term_deposit          1.0       40    Inversión      40.0   \n",
       "27827  short_term_deposit          1.0       40    Inversión      40.0   \n",
       "\n",
       "      entry_date entry_channel  días_encartera   pk_cid country_id  \\\n",
       "22134 2018-04-08           KHK            20.0   100296         ES   \n",
       "22135 2018-04-08           KHK            50.0   100296         ES   \n",
       "22136 2018-04-08           KHK            81.0   100296         ES   \n",
       "27826 2015-01-30           KHM          1337.0  1003705         ES   \n",
       "27827 2015-01-30           KHM          1367.0  1003705         ES   \n",
       "\n",
       "       region_code gender  age deceased       date  Month      days_between  \\\n",
       "22134         28.0      V   46        N 2018-04-28      4            0 days   \n",
       "22135         28.0      V   46        N 2018-05-28      5  30 days 00:00:00   \n",
       "22136         28.0      V   46        N 2018-06-28      6  31 days 00:00:00   \n",
       "27826         28.0      H   33        N 2018-09-28      9            0 days   \n",
       "27827         28.0      H   33        N 2018-10-28     10  30 days 00:00:00   \n",
       "\n",
       "       recurrencia  \n",
       "22134            1  \n",
       "22135            2  \n",
       "22136            3  \n",
       "27826            1  \n",
       "27827            2  "
      ]
     },
     "execution_count": 63,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "full_3.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 84,
   "metadata": {},
   "outputs": [],
   "source": [
    "pd.to_pickle(full_3, './full_3.pickle')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 65,
   "metadata": {},
   "outputs": [],
   "source": [
    "recurrencia_crosstab = pd.crosstab(full_3['recurrencia'], full_3['Ingresos'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 66,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th>Ingresos</th>\n",
       "      <th>10.0</th>\n",
       "      <th>40.0</th>\n",
       "      <th>60.0</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>recurrencia</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>326346</td>\n",
       "      <td>16822</td>\n",
       "      <td>7216</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>318930</td>\n",
       "      <td>19633</td>\n",
       "      <td>6374</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>316815</td>\n",
       "      <td>18083</td>\n",
       "      <td>5655</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>314258</td>\n",
       "      <td>16271</td>\n",
       "      <td>5205</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>311715</td>\n",
       "      <td>15057</td>\n",
       "      <td>4785</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>145</th>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>146</th>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>147</th>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>148</th>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>149</th>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>149 rows × 3 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "Ingresos       10.0   40.0  60.0\n",
       "recurrencia                     \n",
       "1            326346  16822  7216\n",
       "2            318930  19633  6374\n",
       "3            316815  18083  5655\n",
       "4            314258  16271  5205\n",
       "5            311715  15057  4785\n",
       "...             ...    ...   ...\n",
       "145               2      0     0\n",
       "146               1      0     0\n",
       "147               1      0     0\n",
       "148               1      0     0\n",
       "149               1      0     0\n",
       "\n",
       "[149 rows x 3 columns]"
      ]
     },
     "execution_count": 66,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "recurrencia_crosstab"
   ]
  },
  {
   "cell_type": "raw",
   "metadata": {},
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 39,
   "metadata": {},
   "outputs": [],
   "source": [
    "# create a groupby DataFrame by pk_cid\n",
    "prod_pivot_ = full_3.groupby([\"Familia_prod\", \"Productos\"]).size()\\\n",
    ".sort_values(ascending = False).to_frame().reset_index().rename(columns = {0: \"venta_por_product\"})\n",
    "\n",
    "#city_pivot_[\"cumsum_by_city\"] = (city_pivot_[\"clients_per_city\"]/city_pivot_[\"clients_per_city\"].sum()).cumsum()\n",
    "\n",
    "#city_pivot_[\"pct_cities\"] = (1/city_pivot_.shape[0])\n",
    "#city_pivot_[\"pct_cities\"] = city_pivot_[\"pct_cities\"].cumsum()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 40,
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Familia_prod</th>\n",
       "      <th>Productos</th>\n",
       "      <th>venta_por_product</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>AhorroVista</td>\n",
       "      <td>em_acount</td>\n",
       "      <td>4381602</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>AhorroVista</td>\n",
       "      <td>debit_card</td>\n",
       "      <td>562968</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>AhorroVista</td>\n",
       "      <td>payroll_account</td>\n",
       "      <td>329420</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>AhorroVista</td>\n",
       "      <td>emc_account</td>\n",
       "      <td>326961</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Inversión</td>\n",
       "      <td>pension_plan</td>\n",
       "      <td>217802</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "  Familia_prod        Productos  venta_por_product\n",
       "0  AhorroVista        em_acount            4381602\n",
       "1  AhorroVista       debit_card             562968\n",
       "2  AhorroVista  payroll_account             329420\n",
       "3  AhorroVista      emc_account             326961\n",
       "4    Inversión     pension_plan             217802"
      ]
     },
     "execution_count": 40,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "prod_pivot_.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 75,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>pk_cid</th>\n",
       "      <th>recurrencia</th>\n",
       "      <th>Ingresos</th>\n",
       "      <th>venta_por_product</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>999892</td>\n",
       "      <td>72</td>\n",
       "      <td>10.0</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1148318</td>\n",
       "      <td>14</td>\n",
       "      <td>10.0</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>1148318</td>\n",
       "      <td>5</td>\n",
       "      <td>10.0</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>1148318</td>\n",
       "      <td>6</td>\n",
       "      <td>10.0</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>1148318</td>\n",
       "      <td>7</td>\n",
       "      <td>10.0</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "    pk_cid  recurrencia  Ingresos  venta_por_product\n",
       "0   999892           72      10.0                  1\n",
       "1  1148318           14      10.0                  1\n",
       "2  1148318            5      10.0                  1\n",
       "3  1148318            6      10.0                  1\n",
       "4  1148318            7      10.0                  1"
      ]
     },
     "execution_count": 75,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "prod_pivot_2 = full_3.groupby([\"pk_cid\",\"recurrencia\", \"Ingresos\"]).size()\\\n",
    ".sort_values(ascending = False).to_frame().reset_index().rename(columns = {0: \"venta_por_product\"})\n",
    "prod_pivot_2.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 76,
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "prod_pivot_2['Ingresos_prod']=prod_pivot_2[\"Ingresos\"]*prod_pivot_2['venta_por_product']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 77,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>pk_cid</th>\n",
       "      <th>recurrencia</th>\n",
       "      <th>Ingresos</th>\n",
       "      <th>venta_por_product</th>\n",
       "      <th>Ingresos_prod</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>999892</td>\n",
       "      <td>72</td>\n",
       "      <td>10.0</td>\n",
       "      <td>1</td>\n",
       "      <td>10.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1148318</td>\n",
       "      <td>14</td>\n",
       "      <td>10.0</td>\n",
       "      <td>1</td>\n",
       "      <td>10.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>1148318</td>\n",
       "      <td>5</td>\n",
       "      <td>10.0</td>\n",
       "      <td>1</td>\n",
       "      <td>10.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>1148318</td>\n",
       "      <td>6</td>\n",
       "      <td>10.0</td>\n",
       "      <td>1</td>\n",
       "      <td>10.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>1148318</td>\n",
       "      <td>7</td>\n",
       "      <td>10.0</td>\n",
       "      <td>1</td>\n",
       "      <td>10.0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "    pk_cid  recurrencia  Ingresos  venta_por_product  Ingresos_prod\n",
       "0   999892           72      10.0                  1           10.0\n",
       "1  1148318           14      10.0                  1           10.0\n",
       "2  1148318            5      10.0                  1           10.0\n",
       "3  1148318            6      10.0                  1           10.0\n",
       "4  1148318            7      10.0                  1           10.0"
      ]
     },
     "execution_count": 77,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "prod_pivot_2.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 78,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>pk_cid</th>\n",
       "      <th>Productos</th>\n",
       "      <th>Ingresos</th>\n",
       "      <th>venta_por_cliente</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>999892</td>\n",
       "      <td>payroll_account</td>\n",
       "      <td>10.0</td>\n",
       "      <td>17</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1206918</td>\n",
       "      <td>em_acount</td>\n",
       "      <td>10.0</td>\n",
       "      <td>17</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>1207681</td>\n",
       "      <td>em_acount</td>\n",
       "      <td>10.0</td>\n",
       "      <td>17</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>1207682</td>\n",
       "      <td>em_acount</td>\n",
       "      <td>10.0</td>\n",
       "      <td>17</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>1207683</td>\n",
       "      <td>em_acount</td>\n",
       "      <td>10.0</td>\n",
       "      <td>17</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "    pk_cid        Productos  Ingresos  venta_por_cliente\n",
       "0   999892  payroll_account      10.0                 17\n",
       "1  1206918        em_acount      10.0                 17\n",
       "2  1207681        em_acount      10.0                 17\n",
       "3  1207682        em_acount      10.0                 17\n",
       "4  1207683        em_acount      10.0                 17"
      ]
     },
     "execution_count": 78,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "client_pivot_ = full_3.groupby([\"pk_cid\", \"Productos\",\"Ingresos\"]).size()\\\n",
    ".sort_values(ascending = False).to_frame().reset_index().rename(columns = {0: \"venta_por_cliente\"})\n",
    "client_pivot_.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 79,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>pk_cid</th>\n",
       "      <th>Productos</th>\n",
       "      <th>Ingresos</th>\n",
       "      <th>venta_por_cliente</th>\n",
       "      <th>Ingresos_client</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>999892</td>\n",
       "      <td>payroll_account</td>\n",
       "      <td>10.0</td>\n",
       "      <td>17</td>\n",
       "      <td>170.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1206918</td>\n",
       "      <td>em_acount</td>\n",
       "      <td>10.0</td>\n",
       "      <td>17</td>\n",
       "      <td>170.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>1207681</td>\n",
       "      <td>em_acount</td>\n",
       "      <td>10.0</td>\n",
       "      <td>17</td>\n",
       "      <td>170.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>1207682</td>\n",
       "      <td>em_acount</td>\n",
       "      <td>10.0</td>\n",
       "      <td>17</td>\n",
       "      <td>170.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>1207683</td>\n",
       "      <td>em_acount</td>\n",
       "      <td>10.0</td>\n",
       "      <td>17</td>\n",
       "      <td>170.0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "    pk_cid        Productos  Ingresos  venta_por_cliente  Ingresos_client\n",
       "0   999892  payroll_account      10.0                 17            170.0\n",
       "1  1206918        em_acount      10.0                 17            170.0\n",
       "2  1207681        em_acount      10.0                 17            170.0\n",
       "3  1207682        em_acount      10.0                 17            170.0\n",
       "4  1207683        em_acount      10.0                 17            170.0"
      ]
     },
     "execution_count": 79,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "client_pivot_['Ingresos_client']=client_pivot_[\"Ingresos\"]*client_pivot_['venta_por_cliente']\n",
    "client_pivot_.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 80,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>pk_cid</th>\n",
       "      <th>Productos</th>\n",
       "      <th>Ingresos</th>\n",
       "      <th>venta_por_cliente</th>\n",
       "      <th>Ingresos_client</th>\n",
       "      <th>venta_perc_cliente</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>999892</td>\n",
       "      <td>payroll_account</td>\n",
       "      <td>10.0</td>\n",
       "      <td>17</td>\n",
       "      <td>170.0</td>\n",
       "      <td>0.000003</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1206918</td>\n",
       "      <td>em_acount</td>\n",
       "      <td>10.0</td>\n",
       "      <td>17</td>\n",
       "      <td>170.0</td>\n",
       "      <td>0.000005</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>1207681</td>\n",
       "      <td>em_acount</td>\n",
       "      <td>10.0</td>\n",
       "      <td>17</td>\n",
       "      <td>170.0</td>\n",
       "      <td>0.000008</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>1207682</td>\n",
       "      <td>em_acount</td>\n",
       "      <td>10.0</td>\n",
       "      <td>17</td>\n",
       "      <td>170.0</td>\n",
       "      <td>0.000011</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>1207683</td>\n",
       "      <td>em_acount</td>\n",
       "      <td>10.0</td>\n",
       "      <td>17</td>\n",
       "      <td>170.0</td>\n",
       "      <td>0.000014</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "    pk_cid        Productos  Ingresos  venta_por_cliente  Ingresos_client  \\\n",
       "0   999892  payroll_account      10.0                 17            170.0   \n",
       "1  1206918        em_acount      10.0                 17            170.0   \n",
       "2  1207681        em_acount      10.0                 17            170.0   \n",
       "3  1207682        em_acount      10.0                 17            170.0   \n",
       "4  1207683        em_acount      10.0                 17            170.0   \n",
       "\n",
       "   venta_perc_cliente  \n",
       "0            0.000003  \n",
       "1            0.000005  \n",
       "2            0.000008  \n",
       "3            0.000011  \n",
       "4            0.000014  "
      ]
     },
     "execution_count": 80,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "client_pivot_[\"venta_perc_cliente\"] = (client_pivot_[\"venta_por_cliente\"]/client_pivot_[\"venta_por_cliente\"].sum()).cumsum()\n",
    "client_pivot_.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 81,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>pk_cid</th>\n",
       "      <th>Productos</th>\n",
       "      <th>Ingresos</th>\n",
       "      <th>venta_por_cliente</th>\n",
       "      <th>Ingresos_client</th>\n",
       "      <th>venta_perc_cliente</th>\n",
       "      <th>pct_client</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>999892</td>\n",
       "      <td>payroll_account</td>\n",
       "      <td>10.0</td>\n",
       "      <td>17</td>\n",
       "      <td>170.0</td>\n",
       "      <td>0.000003</td>\n",
       "      <td>0.000002</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1206918</td>\n",
       "      <td>em_acount</td>\n",
       "      <td>10.0</td>\n",
       "      <td>17</td>\n",
       "      <td>170.0</td>\n",
       "      <td>0.000005</td>\n",
       "      <td>0.000004</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>1207681</td>\n",
       "      <td>em_acount</td>\n",
       "      <td>10.0</td>\n",
       "      <td>17</td>\n",
       "      <td>170.0</td>\n",
       "      <td>0.000008</td>\n",
       "      <td>0.000006</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>1207682</td>\n",
       "      <td>em_acount</td>\n",
       "      <td>10.0</td>\n",
       "      <td>17</td>\n",
       "      <td>170.0</td>\n",
       "      <td>0.000011</td>\n",
       "      <td>0.000007</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>1207683</td>\n",
       "      <td>em_acount</td>\n",
       "      <td>10.0</td>\n",
       "      <td>17</td>\n",
       "      <td>170.0</td>\n",
       "      <td>0.000014</td>\n",
       "      <td>0.000009</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "    pk_cid        Productos  Ingresos  venta_por_cliente  Ingresos_client  \\\n",
       "0   999892  payroll_account      10.0                 17            170.0   \n",
       "1  1206918        em_acount      10.0                 17            170.0   \n",
       "2  1207681        em_acount      10.0                 17            170.0   \n",
       "3  1207682        em_acount      10.0                 17            170.0   \n",
       "4  1207683        em_acount      10.0                 17            170.0   \n",
       "\n",
       "   venta_perc_cliente  pct_client  \n",
       "0            0.000003    0.000002  \n",
       "1            0.000005    0.000004  \n",
       "2            0.000008    0.000006  \n",
       "3            0.000011    0.000007  \n",
       "4            0.000014    0.000009  "
      ]
     },
     "execution_count": 81,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "client_pivot_[\"pct_client\"] = (1/client_pivot_.shape[0])\n",
    "client_pivot_[\"pct_client\"] = client_pivot_[\"pct_client\"].cumsum()\n",
    "client_pivot_.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# aplicar OHE sobre columnas "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 83,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'pandas.core.frame.DataFrame'>\n",
      "Int64Index: 6254518 entries, 22134 to 89443859\n",
      "Data columns (total 18 columns):\n",
      " #   Column          Dtype         \n",
      "---  ------          -----         \n",
      " 0   Productos       object        \n",
      " 1   Ventas_cant     float64       \n",
      " 2   Precios         int64         \n",
      " 3   Familia_prod    object        \n",
      " 4   Ingresos        float64       \n",
      " 5   entry_date      datetime64[ns]\n",
      " 6   entry_channel   object        \n",
      " 7   días_encartera  float64       \n",
      " 8   pk_cid          object        \n",
      " 9   country_id      object        \n",
      " 10  region_code     float64       \n",
      " 11  gender          object        \n",
      " 12  age             int64         \n",
      " 13  deceased        object        \n",
      " 14  date            datetime64[ns]\n",
      " 15  Month           int64         \n",
      " 16  days_between    object        \n",
      " 17  recurrencia     int64         \n",
      "dtypes: datetime64[ns](2), float64(4), int64(4), object(8)\n",
      "memory usage: 1.0+ GB\n"
     ]
    }
   ],
   "source": [
    "full_3.info()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "## Selección del número óptimo de Clusters"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "CALCULATE_ELBOW = True\n",
    "\n",
    "if CALCULATE_ELBOW:\n",
    "    st = time.time()\n",
    "\n",
    "    sse = {}\n",
    "\n",
    "    for k in range(2, 15):\n",
    "\n",
    "        print(f\"Fitting pipe with {k} clusters\")\n",
    "        cluster_model = KMeans(n_clusters = k)\n",
    "        cluster_model.fit(full_2_subset)\n",
    "\n",
    "        sse[k] = cluster_model.inertia_\n",
    "\n",
    "    et = time.time()\n",
    "    print(\"Elbow curve took {} minutes.\".format(round((et - st)/60), 2))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 58,
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'CALCULATE_ELBOW' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-58-c167617235de>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[1;32m----> 1\u001b[1;33m \u001b[1;32mif\u001b[0m \u001b[0mCALCULATE_ELBOW\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m      2\u001b[0m     \u001b[0mfig\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mplt\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mfigure\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mfigsize\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;33m(\u001b[0m\u001b[1;36m16\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;36m8\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      3\u001b[0m     \u001b[0max\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mfig\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0madd_subplot\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      4\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      5\u001b[0m     \u001b[0mx_values\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mlist\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0msse\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mkeys\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mNameError\u001b[0m: name 'CALCULATE_ELBOW' is not defined"
     ]
    }
   ],
   "source": [
    "if CALCULATE_ELBOW:\n",
    "    fig = plt.figure(figsize = (16, 8))\n",
    "    ax = fig.add_subplot()\n",
    "\n",
    "    x_values = list(sse.keys())\n",
    "    y_values = list(sse.values())\n",
    "\n",
    "    ax.plot(x_values, y_values, label = \"Inertia/dispersión de los clústers\")\n",
    "    fig.suptitle(\"Variación de la dispersión de los clústers en función de la k\", fontsize = 16);"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [],
   "source": [
    "class ArrayToDataFrame(BaseEstimator, TransformerMixin):\n",
    "    '''\n",
    "    Clase que transforma un array en un DataFrame.\n",
    "    Necesita como parámetros el nombre de las columnas y el índice.\n",
    "    '''\n",
    "    \n",
    "    def __init__(self, columns, index = None):\n",
    "        self.columns = columns\n",
    "        self.index = index\n",
    "        \n",
    "    def fit(self, X, y = None):\n",
    "        return self\n",
    "    \n",
    "    def transform(self, X, y = None):\n",
    "        \n",
    "        if self.index != None:\n",
    "            df = pd.DataFrame(X, columns = self.columns, index = self.index)\n",
    "            \n",
    "        else:\n",
    "            df = pd.DataFrame(X, columns = self.columns)\n",
    "            \n",
    "        return df"
   ]
  }
 ],
 "metadata": {
  "interpreter": {
   "hash": "02b54ae4fcef88d4936c518f12e4c1a4a3ccb83eb22d3060789450414c249266"
  },
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  },
  "varInspector": {
   "cols": {
    "lenName": 16,
    "lenType": 16,
    "lenVar": 40
   },
   "kernels_config": {
    "python": {
     "delete_cmd_postfix": "",
     "delete_cmd_prefix": "del ",
     "library": "var_list.py",
     "varRefreshCmd": "print(var_dic_list())"
    },
    "r": {
     "delete_cmd_postfix": ") ",
     "delete_cmd_prefix": "rm(",
     "library": "var_list.r",
     "varRefreshCmd": "cat(var_dic_list()) "
    }
   },
   "types_to_exclude": [
    "module",
    "function",
    "builtin_function_or_method",
    "instance",
    "_Feature"
   ],
   "window_display": false
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
